name: Build Sphinx docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'stable/**'

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Build docs
        shell: bash
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          tox -edocs
