name: Styles check

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run styles check
        shell: bash
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          tox -elint,mypy
